services:
  # Azure TTS API 服务 (基于预构建基础镜像)
  azure-tts-api:
    build:
      context: .
      dockerfile: Dockerfile.api
    container_name: azure-tts-api
    environment:
      # Azure Speech Service 配置
      - SPEECH_KEY=${SPEECH_KEY}
      - SPEECH_REGION=${SPEECH_REGION}
      # 应用配置
      - OUTPUT_DIR=/app/output
      - PORT=8080
      - GIN_MODE=release
    ports:
      - "8080:8080"
    volumes:
      # 挂载输出目录到主机
      - ./output:/app/output
    restart: unless-stopped
    networks:
      - azure-speech-net
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  go-modules:

networks:
  azure-speech-net:
    driver: bridge